// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD6y_NEylYSJlpwh3w2qz91_6aHfgodF5k',
    appId: '1:251535862149:web:f6c14ad3f69d46ad92fcec',
    messagingSenderId: '251535862149',
    projectId: 'agenda-personalizada-9e6d5',
    authDomain: 'agenda-personalizada-9e6d5.firebaseapp.com',
    storageBucket: 'agenda-personalizada-9e6d5.appspot.com',
    measurementId: 'G-KFYKKB4BK6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA8uaNOlrddhFTqKo6E6LKARDYuulUPv7U',
    appId: '1:251535862149:android:45877acae6efef8a92fcec',
    messagingSenderId: '251535862149',
    projectId: 'agenda-personalizada-9e6d5',
    storageBucket: 'agenda-personalizada-9e6d5.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAmFidkA6-fIfec4Zuchy8Ugt3oU-80Rg4',
    appId: '1:251535862149:ios:0fc11ab483a21c9b92fcec',
    messagingSenderId: '251535862149',
    projectId: 'agenda-personalizada-9e6d5',
    storageBucket: 'agenda-personalizada-9e6d5.appspot.com',
    iosClientId: '251535862149-acq1q4vepvqn3nt4da5mnnd398r8dr12.apps.googleusercontent.com',
    iosBundleId: 'com.example.agendaPersonalizada',
  );
}
